services:
  - postgresql
before_script:
  - psql -c 'create database flight_test;' -U postgres
language: python
python:
  - "3.6"
# install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# run tests
script:
  - nosetests --with-coverage
after_success:
  - coveralls
